enum Genere {
    COMMEDIA = 'COMMEDIA',
    AZIONE = 'AZIONE',
    AVVENTURA = 'AVVENTURA',
    HORROR = 'HORROR',
    DRAMMATICO = 'DRAMMATICO',
    BIOGRAFICO = 'BIOGRAFICO',
    MUSICAL = 'MUSICAL',
    THRILLER = 'THRILLER',
    FANTASY = 'FANTASY',
    DOCUMENTARIO = 'DOCUMENTARIO',
    SENTIMENTALE = 'SENTIMENTALE',
    CRIME = 'CRIME'
}