export enum Mansione{
    MAGAZZINO = "MAGAZZINO",
    HR = "HR",
    SOCIALMEDIAMANAGER = "SOCIALMEDIAMANAGER",
    BIGLIETTERIA = "BIGLIETTERIA",
    DIRETTORE = "DIRETTORE",
    CONTABILE = "CONTABILE",
    PROIEZIONE = "PROIEZIONE"
}